# Generated by Django 4.1.7 on 2023-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shoppingcart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
